export default {
  API_HOST: String(process.env.REACT_APP_API_HOST),
  GITHUB_CLIENT_ID: String(process.env.REACT_APP_GITHUB_CLIENT_ID),
  GITHUB_CLIENT_SECRET: String(process.env.REACT_APP_GITHUB_CLIENT_SECRET),
  GITHUB_AUTH_URL: String(process.env.REACT_APP_GITHUB_AUTH_URL),
  GOOGLE_CLIENT_ID: String(process.env.REACT_APP_GOOGLE_CLIENT_ID)
}